/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/sections/AboutSection.vue')['default']
    CertificationsSection: typeof import('./src/components/sections/CertificationsSection.vue')['default']
    ContactSection: typeof import('./src/components/sections/ContactSection.vue')['default']
    ExperienceSection: typeof import('./src/components/sections/ExperienceSection.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hero: typeof import('./src/components/sections/Hero.vue')['default']
    HeroSection: typeof import('./src/components/sections/HeroSection.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    ProjectsSection: typeof import('./src/components/sections/ProjectsSection.vue')['default']
    ScrollProgress: typeof import('./src/components/layout/ScrollProgress.vue')['default']
    SkillsSection: typeof import('./src/components/sections/SkillsSection.vue')['default']
    Timeline: typeof import('./src/components/ui/Timeline.vue')['default']
    TimelineFeed: typeof import('./src/components/ui/TimelineFeed.vue')['default']
    TimelineFeeds: typeof import('./src/components/ui/timelineFeeds.vue')['default']
    TimelineItem: typeof import('./src/components/ui/TimelineItem.vue')['default']
  }
}
